name: metrics-one
services:
  database: 
    container_name: database
    build:
      context: ./backend/
      target: database
    restart: always
    volumes:
      - ./backend/database/data:/var/lib/postgresql/data
    networks:
      - network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DBNAME}
    ports:
      - 5432:5432 # Exposed for development

  api:
    container_name: api
    build:
      context: ./backend/
      target: api
    networks:
      - network
    environment:
      - SERVER.HTTP.HOST=0.0.0.0
      - SERVER.HTTP.PORT=${API_HTTP_PORT}
      - SERVER.GRPC.HOST=0.0.0.0
      - SERVER.GRPC.PORT=${API_GRPC_PORT}
      - DB.USER=${DB_USER}
      - DB.PASSWORD=${DB_PASSWORD}
      - DB.HOST=database
      - DB.PORT=5432
      - DB.DBNAME=${DB_DBNAME}
      - DB.POOL_MAX_SIZE=${DB_POOL_MAX_SIZE}
      - WORKER.HOST=worker
      - WORKER.PORT=${WORKER_PORT}
      - RUST_LOG=${RUST_LOG}
    ports:
      - ${API_HTTP_PORT}:${API_HTTP_PORT}
      - ${API_GRPC_PORT}:${API_GRPC_PORT} # Exposed for development

  worker:
    container_name: worker
    build:
      context: ./backend/
      target: worker
    networks:
      - network
    environment:
      - SERVER.HOST=0.0.0.0
      - SERVER.PORT=${WORKER_PORT}
      - API.HOST=api
      - API.PORT=${API_GRPC_PORT}
      - LIVETIMING_URL=${LIVETIMING_URL}
      - RUST_LOG=${RUST_LOG}
    ports:
      - ${WORKER_PORT}:${WORKER_PORT} # Exposed for development

  web:
    container_name: web
    build: 
      context: ./frontend/
      target: web
    networks:
      - network
    environment:
      - NODE_ENV=production
      - API_HOST=${API_HOST}
      - API_PORT=${API_HTTP_PORT}
      - IMAGE_URL=${IMAGE_URL}
    ports:
      - ${WEB_PORT}:3000 

networks:
  network: 
    driver: bridge
